export const options = [
    { label: "General Knowledge", value: "9" },
    { label: "Books", value: "10" },
    { label: "Films", value: "11" },
    { label: "Music", value: "12" },
    { label: "Musicals & Theatres", value: "13" },
    { label: "Television", value: "14" },
    { label: "Video Games", value: "15" },
    { label: "Board Games", value: "16" },
    { label: "Science & Nature", value: "17" },
    { label: "Computers", value: "18" },
    { label: "Mathematics", value: "19" },
    { label: "Mythology", value: "20" },
    { label: "Sports", value: "21" },
    { label: "Geography", value: "22" },
    { label: "History", value: "23" },
    { label: "Politics", value: "24" },
    { label: "Art", value: "25" },
    { label: "Celebrities", value: "26" },
    { label: "Animals", value: "27" },
    { label: "Vehicles", value: "28" },
    { label: "Comics", value: "29" },
    { label: "Gadgets", value: "30" },
    { label: "Anime & Manga", value: "32" },
    { label: "Cartoon & Animations", value: "33" },
];

export const categoryMaps = new Map([
    ["9", "General Knowledge"],
    ["10", "Books"],
    ["11", "Films"],
    ["12", "Music"],
    ["13", "Musicals & Theatres"],
    ["14", "Television"],
    ["15", "Video Games"],
    ["16", "Board Games"],
    ["17", "Science & Nature"],
    ["18", "Computers"],
    ["19", "Mathematics"],
    ["20", "Mythology"],
    ["21", "Sports"],
    ["22", "Geography"],
    ["23", "History"],
    ["24", "Politics"],
    ["25", "Art"],
    ["26", "Celebrities"],
    ["27", "Animals"],
    ["28", "Vehicles"],
    ["29", "Comics"],
    ["30", "Gadgets"],
    ["32", "Anime & Manga"],
    ["33", "Cartoon & Animations"]
]);

export const entityTable = {
    // Add more named entities as needed
    "sup2": '²',
    "sup3": '³',
    "aacute": 'á',
    "uacute": 'ú',
    "eacute": 'é',
    "oacute": 'ó',
    "atilde": 'ã',
    "ntilde": 'ñ',
    "quot": '"',
    "amp": '&',
    "lt": '<',
    "gt": '>',
    "laquo": '«',
    "rdquo": '”',
    'bdquo': '„',
    "hellip": '…',
    "rsquo": "’",
    "pi": 'π',
    "Pi": 'Π',
    "theta": 'θ',
    "alpha": 'α',
    "beta": 'β',
    "gamma": 'γ',
    "delta": 'δ',
    "epsilon": 'ε',
    "Omega": 'Ω',
    "Sigma": 'Σ',
    "Lambda": 'Λ',
    "Omicron": 'Ο',
    "Nu": 'Ν',
    "Mu": 'Μ',
    // ... other entities ...
};